name: Build and Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Pipeline
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.401
      - name: Install dependencies
        run: dotnet restore
      - name: Build Release
        run: dotnet build amescodes/ShapeCrawler.csproj --configuration Release --no-restore
      - name: Build Debug
        run: dotnet build --configuration Debug --no-restore
      - name: Run tests
        run: dotnet test --configuration Debug --no-restore --verbosity normal -f net6.0
